global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'tc-api'
    scheme: https
    metrics_path: /api/v2/metrics
    static_configs:
      - targets:
          - $TC_API_HOST
